/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.OrderManagementUI;

import Utils.CustomJButton;
import Utils.CustomJComboBox;
import Utils.CustomJTable;
import Utils.CustomJTextField;
import java.awt.Color;
import java.awt.Font;
import javax.swing.Icon;
import javax.swing.JFrame;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author NGOC BAU
 */
public class BillDetailUI extends javax.swing.JFrame {

    /**
     * Creates new form BillDetailUI
     */
    CustomJTable customJtable = new CustomJTable();
    CustomJTextField customJTextField = new CustomJTextField();
    CustomJButton customJButton = new CustomJButton();
    CustomJComboBox customJComboBox = new CustomJComboBox();

    public BillDetailUI() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CHI TIẾT HÓA ĐƠN");
        customJtable.setHeaderHeight(30);
        customJtable.setHedaerBackgroundColor(new Color(30, 39, 46));
        customJtable.setHeaderForegroundColor(Color.WHITE);
        customJtable.setHeaderBorderColor(Color.BLACK);
        customJtable.setHeaderFont("Cambria");
        customJtable.setHeaderFontSize(13);
        customJtable.setHeaderFontStyle(Font.BOLD);
        customJtable.setRowHeight(25);
        customJtable.setCellPadding(5);
        customJtable.custom(table_billDetail_listProductInBill);

        customJTextField.setTextFieldBackgroundColor(Color.WHITE);
        customJTextField.setTextFieldForegroundColor(new Color(30, 39, 46));
        customJTextField.setTextFieldFont("Cambria");
        customJTextField.setTextFieldFontStyle(Font.PLAIN);
        customJTextField.setTextFieldFontSize(13);
        customJTextField.setTextFieldBorderColor(new Color(223, 228, 234));
        customJTextField.setTextFieldBorderWeight(1);
        customJTextField.setTextFieldPadding(5);
        customJTextField.custom(textField_billDetail_billID);
        customJTextField.custom(textField_billDetail_createdTime);
        customJTextField.custom(textField_billDetail_customerID);
        customJTextField.custom(textField_billDetail_customerName);
        customJTextField.custom(textField_billDetail_total);
        customJTextField.custom(textField_billDetail_cusomerAdd);
        customJTextField.custom(textField_billDetail_note);
        customJTextField.custom(textField_billDetail_customerCity);

        customJButton.setButtonForegroundColor(Color.WHITE);
        customJButton.setButtonFont("Cambria");
        customJButton.setButtonFontStyle(Font.BOLD);
        customJButton.setButtonFontSize(12);
        customJButton.setButtonBorderColor(Color.WHITE);
        customJButton.setButtonBorderWeight(0);
        customJButton.setButtonBorderRadius(10);
        IconFontSwing.register(FontAwesome.getIconFont());

        customJButton.setButtonBackgroundColor(Color.RED);
        customJButton.custom(button_billDetail_close);

        customJButton.setButtonBackgroundColor(new Color(255, 242, 0));
        Icon iconEditBill = IconFontSwing.buildIcon(FontAwesome.PENCIL, 17, Color.WHITE);
        customJButton.setButtonIcon(iconEditBill);
        customJButton.custom(button_billDetail_editBill);

        customJButton.setButtonBackgroundColor(Color.darkGray);
        Icon iconPrintBill = IconFontSwing.buildIcon(FontAwesome.PRINT, 17, Color.WHITE);
        customJButton.setButtonIcon(iconPrintBill);
        customJButton.custom(button_billDetail_printBill);

//        customJButton.setButtonBackgroundColor(Color.blue);
//        Icon iconRefresh = IconFontSwing.buildIcon(FontAwesome.REFRESH, 17, Color.WHITE);
//        customJButton.setButtonIcon(iconRefresh);
//        customJButton.custom(button_billDetail_refresh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_billDetail_listProductInBill = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        textField_billDetail_total = new javax.swing.JTextField();
        button_billDetail_close = new javax.swing.JButton();
        button_billDetail_editBill = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        textField_billDetail_billID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        textField_billDetail_createdTime = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        textField_billDetail_customerID = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        textField_billDetail_customerName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        button_billDetail_printBill = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        textField_billDetail_note = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        textField_billDetail_cusomerAdd = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        textField_billDetail_customerCity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 39, 46));
        jLabel1.setText("THÔNG TIN SẢN PHẨM");

        table_billDetail_listProductInBill.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        table_billDetail_listProductInBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"2", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"3", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"4", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"5", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"6", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"7", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"8", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"9", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"},
                {"10", "Trương Thành Đại", "123456", null, "23 Buckinghamshire"}
            },
            new String [] {
                "STT", "Tên Sản Phẩm", "Đơn Giá", "SL", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_billDetail_listProductInBill.setAutoscrolls(false);
        table_billDetail_listProductInBill.setGridColor(new java.awt.Color(223, 228, 234));
        table_billDetail_listProductInBill.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table_billDetail_listProductInBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_billDetail_listProductInBillMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_billDetail_listProductInBill);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 64, 198));
        jLabel11.setText("TỔNG TIỀN:");

        textField_billDetail_total.setEditable(false);
        textField_billDetail_total.setText("2.533.465 đ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(textField_billDetail_total, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(textField_billDetail_total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        button_billDetail_close.setText("ĐÓNG");
        button_billDetail_close.setBorder(null);
        button_billDetail_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_billDetail_close.setFocusable(false);
        button_billDetail_close.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_billDetail_close.setIconTextGap(5);
        button_billDetail_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_billDetail_closeMouseClicked(evt);
            }
        });
        button_billDetail_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_billDetail_closeActionPerformed(evt);
            }
        });

        button_billDetail_editBill.setText("SỬA HÓA ĐƠN");
        button_billDetail_editBill.setBorder(null);
        button_billDetail_editBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_billDetail_editBill.setFocusable(false);
        button_billDetail_editBill.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_billDetail_editBill.setIconTextGap(5);
        button_billDetail_editBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_billDetail_editBillMouseClicked(evt);
            }
        });
        button_billDetail_editBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_billDetail_editBillActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 39, 46));
        jLabel3.setText("THÔNG TIN CHUNG");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        textField_billDetail_billID.setEditable(false);
        textField_billDetail_billID.setBackground(new java.awt.Color(255, 255, 255));
        textField_billDetail_billID.setText("HD23534");
        textField_billDetail_billID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField_billDetail_billID.setEnabled(false);
        textField_billDetail_billID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_billDetail_billIDActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 64, 198));
        jLabel14.setText("Mã Hóa Đơn:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(textField_billDetail_billID)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_billDetail_billID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        textField_billDetail_createdTime.setEditable(false);
        textField_billDetail_createdTime.setBackground(new java.awt.Color(255, 255, 255));
        textField_billDetail_createdTime.setText("25/03/3023");
        textField_billDetail_createdTime.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField_billDetail_createdTime.setEnabled(false);
        textField_billDetail_createdTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_billDetail_createdTimeActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 64, 198));
        jLabel20.setText("Ngày Lập Hóa Đơn:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
            .addComponent(textField_billDetail_createdTime)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_billDetail_createdTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 64, 198));
        jLabel21.setText("Mã Khách Hàng:");

        textField_billDetail_customerID.setEditable(false);
        textField_billDetail_customerID.setBackground(new java.awt.Color(255, 255, 255));
        textField_billDetail_customerID.setText("KH002342");
        textField_billDetail_customerID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField_billDetail_customerID.setEnabled(false);
        textField_billDetail_customerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_billDetail_customerIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addComponent(textField_billDetail_customerID)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_billDetail_customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        textField_billDetail_customerName.setEditable(false);
        textField_billDetail_customerName.setBackground(new java.awt.Color(255, 255, 255));
        textField_billDetail_customerName.setText("Nguyễn Văn A");
        textField_billDetail_customerName.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField_billDetail_customerName.setEnabled(false);
        textField_billDetail_customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_billDetail_customerNameActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 64, 198));
        jLabel23.setText("Tên Khách Hàng:");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addComponent(textField_billDetail_customerName)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_billDetail_customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        button_billDetail_printBill.setText("IN HÓA ĐƠN");
        button_billDetail_printBill.setBorder(null);
        button_billDetail_printBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_billDetail_printBill.setFocusable(false);
        button_billDetail_printBill.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_billDetail_printBill.setIconTextGap(5);
        button_billDetail_printBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_billDetail_printBillActionPerformed(evt);
            }
        });

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 64, 198));
        jLabel22.setText("Ghi Chú:");

        textField_billDetail_note.setEditable(false);
        textField_billDetail_note.setBackground(new java.awt.Color(255, 255, 255));
        textField_billDetail_note.setText("AHGWDWF");
        textField_billDetail_note.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField_billDetail_note.setEnabled(false);
        textField_billDetail_note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_billDetail_noteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(textField_billDetail_note)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_billDetail_note, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 64, 198));
        jLabel24.setText("Địa Chỉ:");

        textField_billDetail_cusomerAdd.setEditable(false);
        textField_billDetail_cusomerAdd.setBackground(new java.awt.Color(255, 255, 255));
        textField_billDetail_cusomerAdd.setText("KH002342");
        textField_billDetail_cusomerAdd.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField_billDetail_cusomerAdd.setEnabled(false);
        textField_billDetail_cusomerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_billDetail_cusomerAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addComponent(textField_billDetail_cusomerAdd)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_billDetail_cusomerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 64, 198));
        jLabel25.setText("Thành Phố:");

        textField_billDetail_customerCity.setEditable(false);
        textField_billDetail_customerCity.setBackground(new java.awt.Color(255, 255, 255));
        textField_billDetail_customerCity.setText("KH002342");
        textField_billDetail_customerCity.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField_billDetail_customerCity.setEnabled(false);
        textField_billDetail_customerCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_billDetail_customerCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addComponent(textField_billDetail_customerCity)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_billDetail_customerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_billDetail_editBill, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_billDetail_close, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_billDetail_printBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_billDetail_editBill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_billDetail_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_billDetail_printBill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_billDetail_listProductInBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_billDetail_listProductInBillMouseClicked

    }//GEN-LAST:event_table_billDetail_listProductInBillMouseClicked

    private void button_billDetail_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_billDetail_closeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_billDetail_closeActionPerformed

    private void button_billDetail_editBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_billDetail_editBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_billDetail_editBillActionPerformed

    private void textField_billDetail_billIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_billDetail_billIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_billDetail_billIDActionPerformed

    private void textField_billDetail_createdTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_billDetail_createdTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_billDetail_createdTimeActionPerformed

    private void textField_billDetail_customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_billDetail_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_billDetail_customerNameActionPerformed

    private void textField_billDetail_customerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_billDetail_customerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_billDetail_customerIDActionPerformed

    private void button_billDetail_printBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_billDetail_printBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_billDetail_printBillActionPerformed

    private void textField_billDetail_noteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_billDetail_noteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_billDetail_noteActionPerformed

    private void textField_billDetail_cusomerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_billDetail_cusomerAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_billDetail_cusomerAddActionPerformed

    private void button_billDetail_editBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_billDetail_editBillMouseClicked
        // TODO add your handling code here:
        EditBillUI editBillUI = new EditBillUI();
        editBillUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_billDetail_editBillMouseClicked

    private void button_billDetail_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_billDetail_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button_billDetail_closeMouseClicked

    private void textField_billDetail_customerCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_billDetail_customerCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_billDetail_customerCityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDetailUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_billDetail_close;
    private javax.swing.JButton button_billDetail_editBill;
    private javax.swing.JButton button_billDetail_printBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_billDetail_listProductInBill;
    private javax.swing.JTextField textField_billDetail_billID;
    private javax.swing.JTextField textField_billDetail_createdTime;
    private javax.swing.JTextField textField_billDetail_cusomerAdd;
    private javax.swing.JTextField textField_billDetail_customerCity;
    private javax.swing.JTextField textField_billDetail_customerID;
    private javax.swing.JTextField textField_billDetail_customerName;
    private javax.swing.JTextField textField_billDetail_note;
    private javax.swing.JTextField textField_billDetail_total;
    // End of variables declaration//GEN-END:variables
}
